version: "3"

networks:
  default:
    external: true
    name: ${TRAEFIK_NETWORK_NAME}
  gitea:
    external: false

volumes:
  gitea:
    driver: local
  db:
    driver: local

services:
  gitea:
    image: gitea/gitea:1.16.5
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__repository__DEFAULT_BRANCH=main
      - GITEA__server__PROTOCOL=http
      - GITEA__server__DOMAIN=${GITEA_HOST}
      - GITEA__server__HTTP_PORT=80
      - GITEA__server__LOCAL_ROOT_URL=http://localhost:80
      - GITEA__server__DISABLE_SSH=true
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=${GITEA_DATABASE_NAME}
      - GITEA__database__USER=${GITEA_DATABASE_USER}
      - GITEA__database__PASSWD=${GITEA_DATABASE_PASSWD}
      - GITEA__webhook__ALLOWED_HOST_LIST=*
    labels:
      - traefik.enable=true
      - traefik.docker.network=${TRAEFIK_NETWORK_NAME}
      - traefik.http.routers.gitea-router.rule=Host(`${GITEA_HOST}`)
      - traefik.http.routers.gitea-router.entrypoints=web
      - traefik.http.routers.gitea-router.service=gitea-service
      - traefik.http.services.gitea-service.loadbalancer.server.port=80
    restart: always
    networks:
      default:
        aliases:
          - ${GITEA_HOST}
      gitea:
        aliases:
         - ""
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${GITEA_DATABASE_ROOT_PASSWD}
      - MYSQL_USER=${GITEA_DATABASE_USER}
      - MYSQL_PASSWORD=${GITEA_DATABASE_PASSWD}
      - MYSQL_DATABASE=${GITEA_DATABASE_NAME}
    networks:
      - gitea
    volumes:
      - db:/var/lib/mysql