version: "3"

networks:
  default:
    external: true
    name: ${TRAEFIK_NETWORK_NAME}

services:
  traefik:
    image: traefik
    restart: "always"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
    networks:
      - default